# Makefile for SimpleShell

# Compiler and compiler flags
CC = gcc
CFLAGS = -Wall -Wextra

# Target executable name
TARGET = SimpleShell

# Source files
SRCS = shell.c

# Object files
OBJS = $(SRCS:.c=.o)

# Default target
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean
